import { NgModule } from '@angular/core';
import { MatButtonModule, 
     MatFormFieldModule, 
     MatInputModule,
     MatDatepickerModule, 
     MatNativeDateModule,
     MatCheckbox,   
     MatCheckboxModule,
     MatSidenavModule,
     MatToolbarModule,
     MatIconModule,
     MatListModule,
     MatTabsModule,
     MatCardModule} from '@angular/material';

@NgModule({
    imports: [  MatButtonModule,
                MatFormFieldModule,
                MatIconModule,
                MatInputModule,
                MatDatepickerModule,
                MatNativeDateModule,
                MatCheckboxModule,
                MatSidenavModule,
                MatToolbarModule,
                MatTabsModule,
                MatCardModule,
                MatListModule],
    exports: [ MatButtonModule,
               MatFormFieldModule,
               MatInputModule,
               MatIconModule,
               MatDatepickerModule,
               MatNativeDateModule,
               MatCheckboxModule,
               MatSidenavModule,
               MatToolbarModule,
               MatTabsModule,
               MatCardModule,
               MatListModule]
})
export class MaterialModule {}
